### PR TITLE
Univ3

### PR DESCRIPTION
**Pull request by Max-RiskHarbor**

### CODE REVIEW

**Comment by vladgovor77771** [comment]
why did you removed fee usage? How then we should use fee for valid routing?

Also, can you explain why you divide lambda/delta/target_price by fee, not multiply in your previous pull request?

**Comment by vladgovor77771** [comment]
btw, @tjdiamandis are you sure that lbfgs-b algo is suitable for uniswap v3? just tried to use real data from blockchain (normalized to $). For V2 works well, but when adding V3, lbfgs-b returns negative net trades or not converges (getting acsend direction is 0 from fortran's impl)

**Comment by tjdiamandis** [comment]
@vladgovor77771 Likely a numerical issue. See the Solution Method section of the docs (https://bcc-research.github.io/CFMMRouter.jl/dev/method/#Extensions-and-notes) and #11 #22 

Scaling for this problem is difficult because trades are often several orders of magnitude smaller than reserves. This is not something we address in this package, which is primarily intended to serve as a reference implementation for the algorithm.

**Comment by vladgovor77771** [comment]
> Scaling for this problem is difficult because trades are often several orders of magnitude smaller than reserves.

well, for v2 it was enough for me to have difference between trades and reserves ~7 orders to get appropriate results from lbfgs-b. But for v3 same type of normalisation of virtual reserves in each tick (so each tick transformed exactly like v2 cfmm) don't work as expected. Is it also can be related to numerical issue?

**Comment by Max-RiskHarbor** [comment]
agg prettier why

**Pull request closed without merging**
